### ISSUE TITLE
Code running problems

### ISSUE THREAD

**Issue by fengzhipeng1** [abudesai/timeVAE#2]
Hello!
Thank you for your code. Why do I get the following error when I run test_vae. py
with open(filename, 'wb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './model/vae_timeVAE_sine_perc_20_iter_0_encoder_wts.h5'

**Comment by koseoyoung** [comment]
```
mkdir model 
mkdir outputs 
```

This helps to fix the errors during running the code.

**Comment by abudesai** [comment]
Based on your note, I have now updated the repo to retain those two missing
folders but ignore their contents.

Thank you for informing me!
Abu Desai

**Comment by HuijieAo** [comment]
> ```
> mkdir model 
> mkdir outputs 
> ```
> 
> This helps to fix the errors during running the code.

I have some problems about parquet files when I run preprocessing codes are as follows:

(TimeVAE) aohuijie@ae0805e8ceb1:~/timeVAE/processing$ python preprocessors.py
Traceback (most recent call last):
File "preprocessors.py", line 403, in
data = pd.read_parquet("History_series_0028C91B.002795_filled.parquet")
File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
return impl.read(
File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
handles = get_handle(
File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'History_series_0028C91B.002795_filled.parquet'

AttributeError Traceback (most recent call last)
Cell In[12], line 1
----> 1 data = pd.read_parquet(cfg.TEST_FORECAST_FILE, columns=['queueid', 'date','callvolume'])
2 data['date'] = pd.to_datetime(data['date'])
3 data.rename(columns={ 'queueid': 'seriesid', 'date': 'ts', 'callvolume': 'v',}, inplace=True)

AttributeError: module 'config.config' has no attribute 'TEST_FORECAST_FILE'

Can you tell me what problems blocking me ?
