### ISSUE TITLE
parquet files problem

### ISSUE THREAD

**Issue by HuijieAo** [abudesai/timeVAE#4]
I have some problems about parquet files when I run preprocessing codes are as follows:

(TimeVAE) aohuijie@ae0805e8ceb1:~/timeVAE/processing$ python preprocessors.py 
Traceback (most recent call last):
  File "preprocessors.py", line 403, in <module>
    data = pd.read_parquet("History_series_0028C91B.002795_filled.parquet")
  File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/parquet.py", line 509, in read_parquet
    return impl.read(
  File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/parquet.py", line 220, in read
    path_or_handle, handles, kwargs["filesystem"] = _get_path_or_handle(
  File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/parquet.py", line 110, in _get_path_or_handle
    handles = get_handle(
  File "/home/aohuijie/miniconda3/envs/TimeVAE/lib/python3.8/site-packages/pandas/io/common.py", line 868, in get_handle
    handle = open(handle, ioargs.mode)
FileNotFoundError: [Errno 2] No such file or directory: 'History_series_0028C91B.002795_filled.parquet'

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[12], line 1
----> 1 data = pd.read_parquet(cfg.TEST_FORECAST_FILE, columns=['queueid', 'date','callvolume'])
      2 data['date'] = pd.to_datetime(data['date'])   
      3 data.rename(columns={ 'queueid': 'seriesid', 'date': 'ts', 'callvolume': 'v',}, inplace=True)

AttributeError: module 'config.config' has no attribute 'TEST_FORECAST_FILE'

Can you tell me what problems blocking me ?

**Comment by abudesai** [comment]
I am sorry about the very late reply to your query. I somehow missed your query altogether. 
The error looks like the parquet file you were trying to read in this line could not be found: `data = pd.read_parquet("History_series_0028C91B.002795_filled.parquet")`. 
Do you have the file in the correct location?
